### PR TITLE
execute handshake after connection opened

### PR DESCRIPTION
**Pull request by yuya373**
if nowait is t, `open-network-stream` or `make-network-process`
function returns without waiting connection opened.
we need to wait executing handshake process until process status
changed to `open`.
we call `websocket-handshake` in sentinel because sentinel function is
executed when process status changed to `open`.

if nowait is nil, `open-network-stream` or `make-network-process`
returns after connection opened.
sentinel function is not executed when process-status changed to
`open`, we have to call `websocket-handshake` in `websocket-open`.

### CODE REVIEW

**Comment by ahyatt** [comment]
Thanks for the pull request! I'd like to make sure I understand.  Before, we didn't actually check the websocket process state before trying to handshake, and after your change, we will only send the handshake when the state is `open`.

Two questions: 1) what is the problem that this caused in practice?  2) do you have FSF papers for copyright assignment?

**Comment by yuya373** [comment]
I received timeout error from server
I think following reasons. 
1. when network is bad, `(proces-send-string "GET..."` executed before connection is opened.
2. though connection is successfully opened, no handshake process is executed
3. server shutdown connection with timeout error

**Comment by yuya373** [comment]
I don’t have FSF-paper. I think. 

https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html
↑I googled FSF-paper and found this.
is this page describes FSF-paper?

**Comment by ahyatt** [comment]
Yes, that's the right page. You should fill this form out: http://git.savannah.gnu.org/cgit/gnulib.git/plain/doc/Copyright/request-disclaim.changes

The project you are contributing to is GNU Elpa (emacs-websocket), since I will take your change and push it to GNU Elpa after I make sure it passes all the tests, etc.  Thank you!

**Comment by yuya373** [comment]
@ahyatt 
I filled out the form and sent assign@gnu.org a day ago,  but no replies.
Is this right way?

**Comment by ahyatt** [comment]
Yes, that should be correct.  Your change is small enough that it should be
OK to accept, maybe without the assignment (I'll look into this).  I'll
accept it for now, but hold off on pushing it to GNU Elpa until you receive
the assignment.  Thanks for the change!

**Comment by yuya373** [comment]
Thanks!
Should I inform you if a reply comes?

**Comment by ahyatt** [comment]
Yes, please do.

**Comment by ahyatt** [comment]
@yuya373 I've emailed assign@gnu.org who hasn't been able to find anything with your name on it.  Would you mind emailing me at ahyatt@gmail.com, so I would have your email address, and then ask assign@gnu.org to look for it?  Or perhaps just send another email like your original to both them and me.

**Pull request merged**
