### PR TITLE
fix create header error when custom-headers-alist contains %s

### PR DESCRIPTION
**Pull request by xhcoding**

### CODE REVIEW

**Comment by ahyatt** [comment]
Thank you for this fix, which looks reasonable.  I had one suggestion, so please take a look at the comment I left.

**Comment by xhcoding** [comment]
Thank you very much, but I didn't see any comments.

**Comment by ahyatt** [comment]
It should be displayed above (it says I started a review and displays the comment).

**Comment by xhcoding** [comment]
I still haven't seen the comments, I attached a screenshot of this web page.

image

**Comment by ahyatt** [comment]
Oh, sorry, I don't use github review a lot, and didn't understand I had to "submit" my review.  Which is now done, so you should see my comment now.

**Comment by ahyatt** [comment]
Thank you for your fix!

**Pull request merged**
